version: 0.1

env:
  variables:
   imagen: wenance/mock-server
phases:
  pre_build:
    commands:
      - echo installing dependencies...
      - wget -O /bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x /bin/jq
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Servername :"$SERVER_NAME"
  build:
    commands:
      - LOCAL_GIT=`git log -1 | grep commit | sed 's/.* //g'`
      - echo $LOCAL_GIT
      - echo Build started on `date`
      - echo Building the Docker image...
      - export GITHUB_COMMIT_URL=https://api.github.com/repos/wenance/mock-server/commits/develop\?access_token\=$GITHUB_TOKEN
      - export GITHUB_TAG_URL=https://api.github.com/repos/wenance/mock-server/tags\?access_token\=$GITHUB_TOKEN
      - export TAG_VERSION=$(curl -X GET $GITHUB_TAG_URL | jq -r .[0].name)
      - export LAST_COMMIT=$(curl -X GET $GITHUB_COMMIT_URL | jq -r .sha)
      - echo $TAG_VERSION
      - echo $LAST_COMMIT
      - docker build -t $imagen .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker images
      - docker tag $imagen $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:`docker images -q $imagen:latest`  
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:`docker images -q $imagen:latest`
      - printf '{"tag":"%s"}' `docker images -q $imagen:latest` > build.json
artifacts:
  files: build.json
cache:
  paths:
    - '/home/node/app/node_modules/**/*'